feat: Rename "register" to "mint"
valory-xyz/autonolas-registry-frontend pull request #133
Opened 2023-02-16 12:06 UTC by mohandast52

<img width="603" alt="a" src="https://user-images.githubusercontent.com/22061815/219485061-c79c8248-448d-45b2-a8a3-d9f5885494d3.png">

<img width="632" alt="b" src="https://user-images.githubusercontent.com/22061815/219485076-00863848-b97c-4171-ac16-3213bbd3f383.png">

<img width="695" alt="c" src="https://user-images.githubusercontent.com/22061815/219485088-b5057199-0df7-49ce-9d3c-e18c1af17c74.png">

DOUBT: what should I rename `Registration` to?

<img width="440" alt="d" src="https://user-images.githubusercontent.com/22061815/219485103-10c42613-ac9a-4034-8ca0-c4eb33de48fa.png">

2023-02-17 09:05 UTC, jmoreira-valory commented
"Pre-Registration, Active Registration, Finished Registration" states in the protocol should NOT change (these registration refer to registration of agent instances in the service).

The idea of changing "Register a Service" etc. is precisely to avoid the confusion between "registering a service in the Autonolas Protocol"   VS   "register agent instances in the service".   The first action is actually "minting an NFT that represents the service", whereas the second action simply associates addresses to an already minted
 service.

2023-02-17 09:06 UTC, jmoreira-valory commented on common-util/List/ListCommon.jsx
> +    <p>To mint, connect to wallet</p>
connect *your* wallet ?

2023-02-17 09:07 UTC, jmoreira-valory commented on common-util/List/RegisterForm/index.jsx
> +            <p>To mint, connect to wallet</p>
*your

2023-02-17 09:08 UTC, jmoreira-valory commented on components/ListOperators/register.jsx
> +      <Title level={2}>Mint Operator</Title>
I am unsure, but if this refers to register an operator on an already minted state, it should be 'register', no?

2023-02-17 09:08 UTC, jmoreira-valory commented on components/ListOperators/register.jsx
> +        <p>To mint, connect to wallet</p>
*your

2023-02-17 09:08 UTC, jmoreira-valory commented on components/ListServices/RegisterForm.jsx
> +            <p>To mint, connect to wallet</p>
*your

2023-02-17 09:10 UTC, jmoreira-valory requested changes
See comments

2023-02-18 14:24 UTC, DavidMinarsch requested changes
Suggest you start this PR fresh. It's a mess to review. @jmoreira-valory please provide more accurate instructions

2023-02-18 14:24 UTC, DavidMinarsch commented on common-util/Details/ServiceState/3rdStepFinishedRegistration/index.jsx
> +const OPTION_1 = 'Creates a new service multisig with currently minted agent instances';
```suggestion
const OPTION_1 = 'Creates a new service multisig with currently registered agent instances';
```
revert

2023-02-18 14:24 UTC, DavidMinarsch commented on common-util/Details/ServiceState/3rdStepFinishedRegistration/index.jsx
> +const OPTION_2 = 'Updates an existent service multisig with currently minted agent instances. Please note that the only service multisig owner must be the current service owner address';
```suggestion
const OPTION_2 = 'Updates an existent service multisig with currently registered agent instances. Please note that the only service multisig owner must be the current service owner address';
```
revert

2023-02-18 14:24 UTC, DavidMinarsch commented on common-util/Details/ServiceState/utils.jsx
> +          notifySuccess('Minted Successfully');
revert

2023-02-18 14:24 UTC, DavidMinarsch commented on common-util/List/ListCommon.jsx
>  export const RegisterMessage = ({ handleCancel }) => (
Mint should only be used on original NFT creation, not sure where these messages below come into play. Please check

2023-02-18 14:24 UTC, DavidMinarsch commented on components/ListOperators/index.jsx
> +          Mint
Here it should be register

2023-02-18 14:24 UTC, DavidMinarsch commented on components/ListOperators/register.jsx
> +        <p>To mint, connect your wallet</p>
revert to register

2023-02-21 11:18 UTC, closed without merging